## Site settings
##############################################
title: "siimple"
version: "3.2.0"
url: "https://docs.siimple.xyz"
## Theme configuration
color: "blue"
## License configuration
license:
    title: "MIT License"
    url: "https://github.com/siimple/siimple/blob/develop/LICENSE"
## Repository configuration
repository:
    url: "https://github.com/siimple/siimple"
    issues: "https://github.com/siimple/siimple/issues"
    contributors: "https://github.com/siimple/siimple/graphs/contributors"
## Navbar links
links:
    - title: "Usage"
      url: "/usage.html"
    - title: "Colors"
      url: "/colors.html"
## Cookies settings
cookies:
    analytics: "UA-70800807-5"
    path: "/"
    domain: ".siimple.xyz"
## Search settings
search:
    entry: "/search.html"
    database: "./assets/search.json"
    title: "Search"
    subtitle: "Search in <strong>siimple</strong> docs"
## Build settings
##############################################
env: "production"
permalink: "none"
theme: "siimple-theme"
# Sass build configuration
sass:
    style: "compressed"
    load_paths: ["../bower_components", "_sass"]
# Exclude files
exclude: ["LICENSE", "Gemfile", "Gemfile.lock"]

