# Build configuration
env: "production"
exclude: ["README.md", "docs.yaml"]

# Site global variables
title: "siimple: minimal CSS framework for flat and clean websites!"
version: "3.1.0-beta.4"
size: "large"

# Global metadata
bugs_url: "https://github.com/siimple/siimple/issues"
code_license: "https://github.com/siimple/siimple/blob/develop/LICENSE.md"
docs_license: "https://creativecommons.org/licenses/by/4.0/"

