# Build configuration
env: "production"
exclude: ["README.md", "docs.yaml"]
sass:
    load_paths:
        - ../scss
        - _sass

# Site global variables
title: "siimple: minimal CSS framework for flat and clean websites!"
welcome_title: "Documentation"
welcome_subtitle: "All that you need to create your website with <strong>siimple</strong>"
version: "3.1.0"
size: "large"

# Global metadata
home_url: "https://www.siimple.xyz"
bugs_url: "https://github.com/siimple/siimple/issues"
team_url: "https://github.com/orgs/siimple/people"
contributors_url: "https://github.com/siimple/siimple/graphs/contributors"

# Licenses
code_license:
    name: "MIT License"
    url: "https://github.com/siimple/siimple/blob/develop/LICENSE.md"
docs_license:
    name: "Creative Commons CC BY 4.0"
    url: "https://creativecommons.org/licenses/by/4.0/"

