# Build settings
env: "production"
theme: "siimple-theme"
permalink: "none" 

# Sass build settings
sass:
    style: "compressed"
    load_paths: ["../bower_components", "_sass"]

# Site settings
title: "siimple"
version: "3.1.1"
base_url: "https://docs.siimple.xyz/"

# Repository settings
repository:
    url: "https://github.com/siimple/siimple"
    contributors: "https://github.com/siimple/siimple/graphs/contributors"
    issues: "https://github.com/siimple/siimple/issues"
    code_license: 
        title: "MIT License"
        url: "https://github.com/siimple/siimple/blob/develop/LICENSE"
    docs_license: 
        title: "Creative Commons CC BY 4.0"
        url: "https://github.com/siimple/siimple/blob/develop/docs/LICENSE"

# Social links
social:
    - id: "github"
      description: "Contribute to our repository"
      url: "https://github.com/siimple/siimple"
    - id: "twitter"
      description: "Follow <strong>@siimplecss</strong> on Twitter"
      url: "https://twitter.com/siimplecss"
    - id: "gitter"
      description: "Join our community chat room"
      url: "https://gitter.im/siimple/siimple"

# Search settings
search:
    entry: "/search.html"
    database: "./assets/search.json"

# Cookies settings
cookies:
    analytics: "UA-70800807-5"
    path: "/"
    domain: ".siimple.xyz"

