# Build configuration
env: "production"
exclude: ["README.md", "docs.yaml"]

# Site global variables
title: "siimple: minimal CSS framework for flat and clean websites!"
version: "3.1.0-beta.4"
size: "large"

